### ISSUE TITLE
Can you help to add some demos?

### ISSUE THREAD

**Issue by bitzhuwei** [MikePopoloski/SharpFont#1]
This project is just what I'm looking for. I'm working on rendering text with opengl and I think this project what I needed. It will help a lot if you add some demos showing how to use this or some documents about it.

**Comment by MikePopoloski** [comment]
The library is still a work in progress, which is why there isn't any documentation yet. There is an example program though that shows how to render text via a GPU.

**Comment by bitzhuwei** [comment]
Thank you! I've forked this project and managed to work with it. 
Do you mean that the library can not yet parse everything in a TTF/OTF file when you say it is still a work in progress? If so, can you show some tips about TTF/OTF file's format or where can I find it so that maybe I can do something about this library too.
Oh ,another question, is parser in C# in this project transformed from FreeType-gl or you started from scratch?

**Comment by bitzhuwei** [comment]
I've got the answer from your code. thanks!

**Comment by MikePopoloski** [comment]
Yeah, sorry. This project is from scratch, not related to FreeType-gl. It can parse most of the TTF format, but not all of the features. For example, no embedded bitmaps yet.

**Comment by bitzhuwei** [comment]
can you show some tips about TTF/OTF file's format or where can I find it so that maybe I can do something about this library too?

**Comment by MikePopoloski** [comment]
The OTF spec is here: https://www.microsoft.com/typography/otspec/default.htm

**Comment by bitzhuwei** [comment]
Thank you again!
