### ISSUE TITLE
Emboldening fonts?

### ISSUE THREAD

**Issue by robertk92** [MikePopoloski/SharpFont#3]
Hi,

I'm using your library in combination with opengl and it works well.
I do stuff like italic, strikeout, underline in my vertices, I was wondering if I can embolden a font using your library? (meaning making it bold artificially instead of loading a separate bold version of a font).

Also another side-question, what formats does this library support?

Thanks!

**Comment by MikePopoloski** [comment]
There's nothing built-in for artificial bolding. You could certainly add such a feature if you found it necessary.

The library supports TTF / OTF files.
