### ISSUE TITLE
Wrong font Image Data

### ISSUE THREAD

**Issue by HierGibtEsDrachen** [MikePopoloski/SharpFont#4]
Im using your Code in my "Game" - Engine, i have some trouble with wrong Image data after 
glTextureSubImage2D.

output should be 

`            

            string[] text = new string[]
            {
                "abcdefgh",
                "ijklmnop",
                "qrstuvwx",
                "yz{}[]()",
                "12345678",
                "910#!?.,",
                ";-+*/^%@",
            };
`
Rendered strings
![string-fonsts](https://user-images.githubusercontent.com/36693858/45918214-d0549f00-be83-11e8-8dfa-76e711e4651d.JPG)

Glyphtable Texture
![texture-bitmap](https://user-images.githubusercontent.com/36693858/45918074-a69a7880-be81-11e8-93a2-c1d5bc642e1f.JPG)

as u can see some Glyph´s are correct and some are not. would help me alot if u could tell me if it´s an error in my program or a bug in your code?!

my OpenGL Texture

`               

        void IGlyphAtlas.Insert(char glyph, int page, int x, int y, int width, int height, IntPtr data)
        {
            if (isdisposed) throw new ObjectDisposedException(nameof(Font));
            if (page > 0) throw new InvalidOperationException("the texture of the font is to small for more glyphs");
            
            internaltexture.Write(data, x, y, width, height);
        }

        public void Write(IntPtr data, int x, int y, int width, int height)
        {
            if (isdisposed) throw new ObjectDisposedException(nameof(Texture));
            GL.BindTexture(Target, textureindex);
            GL.TextureSubImage2D(textureindex, 0, x, y, width, height, Format, Type, data);
            GL.BindTexture(Target, 0);
        }

       TextureAttributes attributes = new TextureAttributes()
       {
           filter = OpenGL.GlFilter.LINEAR,
           format = OpenGL.GLPixelFormat.RED,
           type = OpenGL.GLPixelDataType.UNSIGNED_BYTE,
           wrap = OpenGL.GLTextureWrapMode.CLAMP_TO_EDGE,
           internalformat = OpenGL.GLInternalFormat.R8,
       };

        public Texture(GLTextureTarget target, TextureAttributes attributes, int width, int height)
        {
            Target = target;
            Width = width;
            Height = height;

            textureattributes = attributes;
            textureindex = GL.GenTexture();

            GL.BindTexture(Target, textureindex);
                        GL.TexImage2D(GLTexture2DProxyTarget.TEXTURE_2D, 0, InternalFormat, Width, Height, 0, Format, Type, dataptr);
            GL.GenerateMipmap(Target);

            GL.TexParameteri(Target, GLTextureParameter.TEXTURE_MIN_FILTER, Filter == GlFilter.LINEAR ? GlFilter.LINEAR_MIPMAP_LINEAR : Filter);
            GL.TexParameteri(Target, GLTextureParameter.TEXTURE_MAG_FILTER, Filter);
            GL.TexParameteri(Target, GLTextureParameter.TEXTURE_WRAP_S, Wrap);
            GL.TexParameteri(Target, GLTextureParameter.TEXTURE_WRAP_T, Wrap);
            GL.BindTexture(Target, 0);
        }
`

**Comment by HierGibtEsDrachen** [comment]
Im using the (normal, regular, normal) Arial Font from System Directory on Windows 10, if its important...
this is the output of your generated data. 
[glypedata.txt](https://github.com/MikePopoloski/SharpFont/files/2407976/glypedata.txt)

**Comment by MikePopoloski** [comment]
Unfortunately I don't have time to debug this for you. You'll have to take on the debugging yourself.

**Comment by HierGibtEsDrachen** [comment]
At least an answer :)

**Comment by sgf** [comment]
infact if u want solov ur problem,the best way is post on your project files as zip.
if just give out some info,ppl hard to get reiteration.

**Comment by HierGibtEsDrachen** [comment]
nono dont misunderstand me :) 
it was a clear answer: do it yourself!
if i want to complain i would write something like: at least an answer... fuck u xD
